### ISSUE TITLE
example on using on a user resource?

### ISSUE THREAD

**Issue by codeitlikemiley** [cybercog/laravel-nova-ban#1]
i tried doing something like this

`Boolean::make('Banned')->resolveUsing(function ($user) {
                return $user->banned_at;
            })
                ->exceptOnForms(),`
but when i used actions , it is not reactive can u give example

**Comment by antonkomarev** [comment]
Try this one:
```php
Boolean::make('Is Active', 'banned_at')->values(false, true),
```

I think it's better display inversed value, to have red icon for banned users. It will be more obvious.
