### ISSUE TITLE
Support for Nova v4

### ISSUE THREAD

**Issue by nathan-io** [cybercog/laravel-nova-ban#12]
Thank you for this package! Any plans to support Nova v4?

https://nova.laravel.com/docs/4.0/upgrade.html

**Comment by antonkomarev** [comment]
@nathan-io Yes, but now I don't have time to dive in. If you want to help, push a PR, please. I'll try to review it ASAP.

**Comment by antonkomarev** [comment]
@nathan-io you can try out new [Laravel Nova Ban v2](https://github.com/cybercog/laravel-nova-ban/releases/tag/2.0.0) release.
