### ISSUE TITLE
Unban::fields() and Ban::fields() base class compatibility problem

### ISSUE THREAD

**Issue by tooshay** [cybercog/laravel-nova-ban#13]
After going through the installation process and reloading the Users management page in Nova, I ran into this:

```
Declaration of Cog\Laravel\Nova\Ban\Actions\Ban::fields() must be compatible with Laravel\Nova\Actions\Action::fields(Laravel\Nova\Http\Requests\NovaRequest $request)
```

It looks like both `Ban` and `Unban` need their `fields()` methods updated to include the missing NovaRequest object. 

We're running:
* PHP 8.1
* Laravel 9.1.3
* Nova 4.12
* Ban 4.7
* Nova Ban 1.2

**Comment by tooshay** [comment]
This is a Nova 4 upgrade issue. Oops!

**Comment by Sentoki** [comment]
And now it is broken for nova 3.

**Comment by antonkomarev** [comment]
> And now it is broken for nova 3.

Thanks for the report. We should pin nova version in the latest Nova Ban version then.

Just use Laravel Nova v1. New v2 adds Nova v4 support, nothing more.
