### ISSUE TITLE
Missing Class 'App\User\Ban' Not Found

### ISSUE THREAD

**Issue by JoshReading** [cybercog/laravel-nova-ban#2]
If you manage to get this error message on load after following the instructions add

```
use Cog\Laravel\Nova\Ban\Actions\Ban;
use Cog\Laravel\Nova\Ban\Actions\Unban;
```

Into your Bannable Nova resource

**Comment by antonkomarev** [comment]
Yeah, I should use fully qualified class names in documentation. Thanks @JoshReading!
