### ISSUE TITLE
Update to Laravel 7

### ISSUE THREAD

**Issue by mvdnbrk** [cybercog/laravel-nova-ban#8]
The requirement of `symfony/process: ^4.1` prevents from updating to Laravel v7.

I don't see the need to require `symfony/process`, can be removed as a required dependency.

**Comment by antonkomarev** [comment]
Thanks! [Laravel Nova Ban v1.1.1](https://github.com/cybercog/laravel-nova-ban/releases/tag/1.1.1) has been released with your fix.
